version: '3.8'

networks:
  minha-rede:
    driver: bridge

services:
  database:
    image: postgres:12.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  base: &base
    build: .
    tty: true
    volumes:
      - bundle_cache:/bundle
      - .:/frankenstein:cached
      - ./:/app
    depends_on:
      - database

    environment:
      TZ:          America/Sao_Paulo
      DB_HOST:     database
      DB_NAME:     frankenstein_dev
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RAILS_ENV:   development

  runner:
    <<: *base
    entrypoint: entrypoints/default.sh

  web:
    <<: *base
    hostname: frankenstein-web
    entrypoint: entrypoints/run.sh
    ports:
      - '3000:3000'

volumes:
  bundle_cache: {}
  pg_data: {}
  tmp: {}
